---
proxies:
  - url: https://data.gki.com.ua/api-user/rtile/orto10/ua/
    cache:
      size: 1024M
      ttl: 10y

  - url: https://data.gki.com.ua/api-user/rtile/topo100/ua/
    cache:
      ttl: 10y

  - url: https://geodata.gki.com.ua/api-user/rtile/carto_2756793959475840066/ua/
    cache:
      ttl: 10y

  - url: https://cdn.kadastr.live/tiles/raster/styles/parcels/
    cache:
      ttl: 10d
      plugin:
        name: xyz
        metadata:
          format: '{z}/{x}/{y}.png'
          bounds: [33.842010,47.804854,36.455383,48.676454]
          min_zoom: 0
          max_zoom: 14

  - url: https://cdn.kadastr.live/tiles/raster/
    cache:
      ttl: 1m
      plugin:
        name: plain
        metadata: {}
